spring:
  config:
    active:
      on-profile: qa

build:
  version: "2.0"

accounts:
  message: "Welcome to JMO Devel QA Accounts microservice"
  contact-details:
    name: "JMO Devel"
    email: "jmo.devel@gmail.com"
  on-call-support:
    - (555) 555-1234
    - (555) 555-5678