spring:
  config:
    active:
      on-profile: prod

build:
  version: "1.0"

accounts:
  message: "Welcome to JMO Devel Webhook Accounts microservice"
  contact-details:
    name: "JMO Devel"
    email: "{cipher}7f21bd08af395c74b27df75d806dad9acfaa9be75142b567cdd72acb56cd8efebf962227b4b10c43d23ce6421df45db7"
  on-call-support:
    - (555) 555-1234
    - (555) 555-5678
