build:
  version: "3.0"

server:
  port: 8080

spring:
  application:
    name: accounts

accounts:
  message: "Welcome to JMO Devel Default Accounts ms"
  contact-details:
    name: "JMO Devel"
    email: "jmo.devel@gmail.com"
  on-call-support:
    - (555) 555-1234
    - (555) 555-5678
