build:
  version: "3.0"

server:
  port: 8082

spring:
  application:
    name: cards

cards:
  message: "Welcome to JMO Devel Default Accounts microservice"
  contact-details:
    name: "JMO Devel"
    email: "jmo.devel@gmail.com"
  on-call-support:
    - (555) 555-1234
    - (555) 555-5678
