build:
  version: "3.0"

server:
  port: 8081
spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:file:/tmp/bank;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never

loans:
  message: "Welcome to JMO Devel Default Loans microservice"
  contact-details:
    name: "JMO Devel"
    email: "jmo.devel@gmail.com"
  on-call-support:
    - (555) 555-1234
    - (555) 555-5678