build:
  version: "3.0"

server:
  port: 8081
  
spring:
  application:
    name: loans

loans:
  message: "Welcome to JMO Devel Default Loans microservice"
  contact-details:
    name: "JMO Devel"
    email: "jmo.devel@gmail.com"
  on-call-support:
    - (555) 555-1234
    - (555) 555-5678
